 export const ADD_VIDEOS="ADD_VIDEOS";
 export const REMOVE_VIDEOS="REMOVE_VIDEOS";
 
export const VIDEOS_REQUEST="VIDEO_REQUEST";
export const VIDEOS_SUCCESS="VIDEOS_SUCCESS";
export const VIDEO_ERROR="VIDEO_ERROR";
 